# Generated by ./update.sh - do not update manually!
# Last updated: 2024-02-16
{
  version = "1.0.0.238";
  arm64_sha256 = "debbba2b20585e2b80959b96872cafb500966ce261198ce47abdc54b4efcf111";
  amd64_sha256 = "371026679dba25a033023b4077dc527059d906ec03ea2db05f6fc012ab40c96b";
  loongarch64_sha256 = "8ae25e2cc283eaff09f222b0dfe73238337b3d942b2e98bda74fff9a4234ba31";
}
